steps:
  # Node.js依存関係のインストールとビルド
  - name: 'node:22-slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm ci
        npm run build
    env:
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'

  - name: 'node:22-slim'
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install -g supabase
        supabase migration up
    env:
      - 'SUPABASE_PROJECT_ID=${_SUPABASE_PROJECT_ID}'
    secretEnv:
      - SUPABASE_ACCESS_TOKEN
      - SUPABASE_DB_PASSWORD

  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '.'

  # Artifact Registryへのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:latest'

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# 代入変数（Cloud Build トリガー設定で必須設定）
# 以下の変数は実行時に必ず指定する必要があります：
# _REGION: デプロイ先のリージョン（例: asia-northeast1）
# _SERVICE_NAME: Cloud Run サービス名（例: action-board）
# _REPOSITORY_NAME: Artifact Registry リポジトリ名（例: app）
# _NEXT_PUBLIC_SUPABASE_URL: Supabase プロジェクトURL
# _NEXT_PUBLIC_SUPABASE_ANON_KEY: Supabase 匿名キー

# オプション設定
options:
  # ビルドマシンのスペック
  machineType: 'E2_HIGHCPU_8'
  # ディスクサイズ
  diskSizeGb: 100
  # ログ設定
  logging: CLOUD_LOGGING_ONLY

# タイムアウト設定（30分）
timeout: 1800s

# 成果物として保存するイメージ
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:latest'


availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/SUPABASE_SERVICE_ROLE_KEY/versions/latest'
      env: SUPABASE_ACCESS_TOKEN
    - versionName: 'projects/${PROJECT_ID}/secrets/SUPABASE_DB_PASSWORD/versions/latest'
      env: SUPABASE_DB_PASSWORD
