steps:
  # Node.js依存関係のインストールとビルド
  - name: 'node:22-slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm ci
        npm run build

  - name: 'node:22-slim'
    entrypoint: "bash"
    args:
      - '-c'
      - |
        npx supabase migration up --db-url "postgresql://postgres:$$SUPABASE_DB_PASSWORD@db.${_SUPABASE_PROJECT_ID}.supabase.co:5432/postgres"
    env:
      - 'SUPABASE_PROJECT_ID=${_SUPABASE_PROJECT_ID}'
    secretEnv:
      - SUPABASE_ACCESS_TOKEN
      - SUPABASE_DB_PASSWORD

  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:latest'
      - '.'

  # Artifact Registryへのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:latest'

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy',
      '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# オプション設定
options:
  # ビルドマシンのスペック
  machineType: 'E2_HIGHCPU_8'
  # ディスクサイズ
  diskSizeGb: 100
  # ログ設定
  logging: CLOUD_LOGGING_ONLY

# タイムアウト設定（30分）
timeout: 1800s

# 成果物として保存するイメージ
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:latest'


availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/SUPABASE_SERVICE_ROLE_KEY/versions/latest'
      env: SUPABASE_ACCESS_TOKEN
    - versionName: 'projects/${PROJECT_ID}/secrets/SUPABASE_DB_PASSWORD/versions/latest'
      env: SUPABASE_DB_PASSWORD
