[[review_instructions]]
category = "命名"
instruction = """
変数名に対して、わかりづらい命名があれば指摘してください。また、可読性が低いコードがあれば指摘してください。
ただし、命名や可読性以外に関する指摘はしないでください。
"""

[[review_instructions]]
category = "アクセシビリティ"
instruction = """
サイトのアクセシビリティに関して問題があれば指摘してください。
ただし、アクセシビリティ以外に関する指摘はしないでください。
"""

[[review_instructions]]
category = "保守性"
instruction = """
保守性の観点からコードをレビューしてください。
ただし、命名や可読性に関する指摘はしないでください。
以下は保守性観点の例です。
- DRY
- 密結合, 疎結合
- マジックナンバー
- 純粋関数
- 副作用
- 参照透過性
- 単一責任原則
- 変更容易性
- 再利用性
- テスト容易性
- 隠蔽
- 暗黙の依存
- 凝集度
- Dependency Injection
- カプセル化
- 冪等性
"""

[[review_instructions]]
category = "セキュリティ"
instruction = """
セキュリティ観点からコードをレビューしてください。
ただし、セキュリティに関係がないレビューは除いてください。
以下はセキュリティ観点の例です。
- 入力検証の欠如
- SQLインジェクションの可能性
- クロスサイトスクリプティング（XSS）の脆弱性
- 認証・認可の問題
- 機密情報の漏洩
"""

[[review_instructions]]
category = "パフォーマンス"
instruction = """
セキュリティ観点からコードをレビューしてください。
ただし、10ms以上の遅延が生じる処理などパフォーマンスへの影響度が特に大きいものだけを指摘してください。
以下はパフォーマンス観点の例です。
- 計算量の問題（O(n^2)以上の処理など）
- メモリ使用効率
- N+1問題
"""
